### ISSUE TITLE
Problems with IDate data type after readind a CSV with import

### ISSUE THREAD

**Issue by jllipatz** [gesistsa/rio#293] opened 2021-12-09 11:04 UTC
Hello,

I am experiencing non deterministic problems with a data frame containing an IDate column. In the following example I kept only two columns of the original file (donnees-hospitalieres-covid19-2021-12-08-19h05.csv or the same for a different date from https://www.data.gouv.fr/fr/datasets/donnees-hospitalieres-relatives-a-lepidemie-de-covid-19/). The file was read using `import` without additional option.
Replacing the call to dplyr by `df2 <- df[df$sexe==0,]` make the things go well again. So I don't really know where is the problem : in rio, in dplyr or in the IDate type from data.table.

 **If the problem is related with the IDate type wouldn't it be possible to use the standard type Date instead, overriding what fread did?**

From a fresh session under R 4.1.1 :
```
> library(dplyr)

Attachement du package : ‘dplyr’

Les objets suivants sont masqués depuis ‘package:stats’:

    filter, lag

Les objets suivants sont masqués depuis ‘package:base’:

    intersect, setdiff, setequal, union

> df <- readRDS("U:/PbIDate.RDS")
> str(df)
'data.frame':   191540 obs. of  2 variables:
 $ sexe: int  0 1 2 0 1 2 0 1 2 0 ...
 $ jour: IDate, format: "2020-03-18" "2020-03-18" ...
> df2 <- filter(df,sexe==0)
> df$b <- df$jour-365
> df2$b <- df2$jour-365

> library(rio)
The following rio suggested packages are not installed: ‘arrow’, ‘hexView’, ‘jsonlite’, ‘pzfx’, ‘readODS’, ‘rmarkdown’, ‘rmatio’
Use 'install_formats()' to install them
> df <- readRDS("U:/PbIDate.RDS")
> str(df)
'data.frame':   191540 obs. of  2 variables:
 $ sexe: int  0 1 2 0 1 2 0 1 2 0 ...
 $ jour: IDate, format: "2020-03-18" "2020-03-18" ...
> df2 <- filter(df,sexe==0)
> df$b <- df$jour-365
> df2$b <- df2$jour-365
Erreur dans `-.IDate`(df2$jour, 365) : 
  Internal error: storage mode of IDate is somehow no longer integer
```

**Comment by jsonbecker** [comment] 2022-05-04 21:40
I can't reproduce this issue:

```r
library(rio)
download.file('https://www.data.gouv.fr/fr/datasets/r/63352e38-d353-4b54-bfd1-f1b3ee1cabd7',\040destfile\040=\040'covid.csv')
df <-import('covid.csv')
df$jour
sapply(df,class)
export(df, format = 'RDS')
import('df.rds')
df <- import('df.rds')
df$jour
```

All works fine for me.


```r
R version 4.1.0 (2021-05-18)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 12.3

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rio_0.5.29

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3      fansi_1.0.3       utf8_1.2.2        crayon_1.5.1
 [5] cellranger_1.1.0  lifecycle_1.0.1   magrittr_2.0.2    zip_2.2.0
 [9] pillar_1.7.0      stringi_1.7.6     rlang_1.0.2       cli_3.2.0
[13] readxl_1.3.1      curl_4.3.2        data.table_1.14.2 vctrs_0.3.8
[17] ellipsis_0.3.2    openxlsx_4.2.5    tools_4.1.0       forcats_0.5.1
[21] foreign_0.8-81    glue_1.6.2        hms_1.1.1         compiler_4.1.0
[25] pkgconfig_2.0.3   haven_2.4.1       tibble_3.1.6
```

**Comment by schochastics** [comment] 2023-09-11 08:02
Ok this appears to be an open issue in vctrs: https://github.com/r-lib/vctrs/issues/1781
I will close this here

**Closed by schochastics** 2023-09-11 08:02 UTC

**Comment by chainsawriot** [comment] 2023-09-11 08:04
@schochastics Thank you very much for the investigation. 

I tried `dtplyr` also, the same.

**Comment by jsonbecker** [comment] 2023-09-11 14:52
Oh fascinating!
